=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/final_project/books.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT shelf (name,book+)*>

<!ELEMENT name (#PCDATA)>

<!ELEMENT book (title,author,pubdate,genre,value)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pubdate (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== AIMoney808/SchoolProjects/MCC/INFO_2351/final_project/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE shelf SYSTEM "books.dtd">
<shelf>
    <name>Books on the Shelf</name>
    <book>
        <title>Mortal Engines</title>
        <author>Philip Reeve</author>
        <pubdate>2001</pubdate>
        <genre>SciFi</genre>
        <value>$9.99</value>
    </book>
    <book>
        <title>Shadow of the Torturer</title>
        <author>Gene Wolf</author>
        <pubdate>1980</pubdate>
        <genre>SciFi</genre>
        <value>$19.99</value>
    </book>
    <book>
        <title>Treasure Island</title>
        <author>Robert Luis Stevenson</author>
        <pubdate>1947</pubdate>
        <genre>AdvFi</genre>
        <value>$12.99</value>
    </book>
    <book>
        <title>The Dark Tower: The Gunslinger</title>
        <author>Stephen King</author>
        <pubdate>1982</pubdate>
        <genre>Dark Fantasy</genre>
        <value>$15.97</value>
    </book>
    <book>
        <title>Percy Jackson and the Olympians: The Lightning Thief</title>
        <author>Rick Riordan</author>
        <pubdate>2005</pubdate>
        <genre>Greek Myth/Fiction</genre>
        <value>$5.97</value>
    </book>
</shelf>
