=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/final_project/movies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="selection">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" maxOccurs="unbounded"/>
                <xs:element ref="movie" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="producer"/>
                <xs:element ref="releaseDate"/>
                <xs:element ref="genre"/>
                <xs:element ref="runTime"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="title">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3"/>
                <xs:maxLength value="30"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="producer" type="xs:string"/>
    <xs:element name="releaseDate" type="xs:date"/>
    <xs:element name="genre" type="xs:string"/>
    <xs:element name="runTime">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{1}\h\ \d{1,2}\m"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/final_project/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<selection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="movies.xsd">
    <name>Movies in the Selection</name>
    <movie>
        <title>Shrek</title>
        <producer>DreamWorks Animation</producer>
        <releaseDate>2001-04-22</releaseDate>
        <genre>Comedy/Fantasy</genre>
        <runTime>1h 30m</runTime>
    </movie>
    <movie>
        <title>The Matrix</title>
        <producer>Warner Bros. Pictures</producer>
        <releaseDate>1999-03-31</releaseDate>
        <genre>Action/SciFi</genre>
        <runTime>2h 16m</runTime>
    </movie>
    <movie>
        <title>Underworld</title>
        <producer>Sony Pictures</producer>
        <releaseDate>2003-09-19</releaseDate>
        <genre>Action/Horror</genre>
        <runTime>2h 1m</runTime>
    </movie>
    <movie>
        <title>Terminator 2: Judgment Day</title>
        <producer>TriStar Pictures</producer>
        <releaseDate>1991-06-03</releaseDate>
        <genre>Action/Sci-fi</genre>
        <runTime>2h 15m</runTime>
    </movie>
    <movie>
        <title>Back to the Future</title>
        <producer>Universal Pictures</producer>
        <releaseDate>1985-07-03</releaseDate>
        <genre>Comedy/Sci-fi</genre>
        <runTime>1h 56m</runTime>
    </movie>
</selection>
