=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/final_project/music.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="tracks">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" maxOccurs="unbounded"/>
                <xs:element ref="album" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="album">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="author"/>
                <xs:element ref="releaseDate"/>
                <xs:element ref="genre"/>
                <xs:element ref="trackCount"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="title">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="3"/>
                <xs:maxLength value="25"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="author" type="xs:string"/>
    <xs:element name="releaseDate" type="xs:date"/>
    <xs:element name="genre" type="xs:string"/>
    <xs:element name="trackCount">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{1,2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== AIMoney808/SchoolProjects/MCC/INFO_2351/final_project/music.xml
<?xml version="1.0" encoding="UTF-8"?>
<tracks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="music.xsd">
    <name>Albums in the Mix</name>
    <album>
        <title>Chaotic Dreams</title>
        <author>salad</author>
        <releaseDate>2021-12-03</releaseDate>
        <genre>Ambient/Drum+Bass</genre>
        <trackCount>13</trackCount>
    </album>
    <album>
        <title>Random Access Memories</title>
        <author>Daft Punk</author>
        <releaseDate>2013-05-17</releaseDate>
        <genre>Disco/funk</genre>
        <trackCount>13</trackCount>
    </album>
    <album>
        <title>Nu Radio!</title>
        <author>Deko</author>
        <releaseDate>2021-12-23</releaseDate>
        <genre>Hip-Hop/Rap</genre>
        <trackCount>33</trackCount>
    </album>
    <album>
        <title>The Maze To Nowhere</title>
        <author>Lorn</author>
        <releaseDate>2014-08-27</releaseDate>
        <genre>Dance/Electronic</genre>
        <trackCount>12</trackCount>
    </album>
    <album>
        <title>vignette</title>
        <author>Frums</author>
        <releaseDate>2020-07-03</releaseDate>
        <genre>Electronic</genre>
        <trackCount>20</trackCount>
    </album>
</tracks>
