=== AIMoney808/SchoolProjects/MCC/INFO_2351/mod3.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT house (inventory)>
<!ELEMENT inventory (room)*>
<!ELEMENT room (roomName*,item)*>
<!ELEMENT roomName (#PCDATA)>

<!ELEMENT item (category,itemType,itemColor,itemSize,quantity)>
<!ELEMENT category (#PCDATA)>
<!ELEMENT itemType (#PCDATA)>
<!ELEMENT itemColor (#PCDATA)>
<!ELEMENT itemSize (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== AIMoney808/SchoolProjects/MCC/INFO_2351/Module2_Assignment_XMLInventory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE house SYSTEM "mod3.dtd">
<house>
	<inventory>
		<room>
			<roomName>Living Room</roomName>
			<item>
				<category>Furniture</category>
				<itemType>Recliner</itemType>
				<itemColor>Brown Leather</itemColor>
				<itemSize>Large</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Recliner</itemType>
				<itemColor>Gray Green</itemColor>
				<itemSize>Large</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Sofa</itemType>
				<itemColor>Brown Leather</itemColor>
				<itemSize>Large</itemSize>
				<quantity>1</quantity>
			</item>
		</room>
		<room>
			<roomName>Dining Room</roomName>
			<item>
				<category>Furniture</category>
				<itemType>Table</itemType>
				<itemColor>Cherrywood</itemColor>
				<itemSize>Large</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>CupBoard</category>
				<itemType>Wood</itemType>
				<itemColor>Oak</itemColor>
				<itemSize>Tall</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Chair</itemType>
				<itemColor>Medium Brown With Tan Seat</itemColor>
				<itemSize>Medium</itemSize>
				<quantity>6</quantity>
			</item>
		</room>
		<room>
			<roomName>Bedroom</roomName>
			<item>
				<category>Furniture</category>
				<itemType>Shelf</itemType>
				<itemColor>Press Board</itemColor>
				<itemSize>Tall</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Bed</itemType>
				<itemColor>Black</itemColor>
				<itemSize>Large</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Chair</itemType>
				<itemColor>Black</itemColor>
				<itemSize>Medium</itemSize>
				<quantity>1</quantity>
			</item>
			<item>
				<category>Furniture</category>
				<itemType>Desk</itemType>
				<itemColor>Black</itemColor>
				<itemSize>Medium</itemSize>
				<quantity>1</quantity>
			</item>
		</room>
	</inventory>
</house>
