=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/100_Records.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Employees (Staff)*>

<!ELEMENT Staff (Emp_ID,Name_Prefix,First_Name,Middle_Initial,Last_Name,Gender,
    E_Mail,Father_s_Name,Mother_s_Name,Mother_s_Maiden_Name,Date_of_Birth,
    Time_of_Birth,Age_in_Yrs.,Weight_in_Kgs.,Date_of_Joining,Quarter_of_Joining,Half_of_Joining,Year_of_Joining,
    Month_of_Joining,Month_Name_of_Joining,Short_Month,Day_of_Joining,DOW_of_Joining,Short_DOW,Age_in_Company__Years_,
    Salary,Last___Hike,SSN,Phone_No._,Place_Name,County,City,State,Zip,Region,User_Name,Password)>

<!ELEMENT Emp_ID (#PCDATA)>
<!ELEMENT Name_Prefix (#PCDATA)>
<!ELEMENT First_Name (#PCDATA)>
<!ELEMENT Middle_Initial (#PCDATA)>
<!ELEMENT Last_Name (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT E_Mail (#PCDATA)>
<!ELEMENT Father_s_Name (#PCDATA)>
<!ELEMENT Mother_s_Name (#PCDATA)>
<!ELEMENT Mother_s_Maiden_Name (#PCDATA)>
<!ELEMENT Date_of_Birth (#PCDATA)>
<!ELEMENT Time_of_Birth (#PCDATA)>
<!ELEMENT Age_in_Yrs. (#PCDATA)>
<!ELEMENT Weight_in_Kgs. (#PCDATA)>
<!ELEMENT Date_of_Joining (#PCDATA)>
<!ELEMENT Quarter_of_Joining (#PCDATA)>
<!ELEMENT Half_of_Joining (#PCDATA)>
<!ELEMENT Year_of_Joining (#PCDATA)>
<!ELEMENT Month_of_Joining (#PCDATA)>
<!ELEMENT Month_Name_of_Joining (#PCDATA)>
<!ELEMENT Short_Month (#PCDATA)>
<!ELEMENT Day_of_Joining (#PCDATA)>
<!ELEMENT DOW_of_Joining (#PCDATA)>
<!ELEMENT Short_DOW (#PCDATA)>
<!ELEMENT Age_in_Company__Years_ (#PCDATA)>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Last___Hike (#PCDATA)>
<!ELEMENT SSN (#PCDATA)>
<!ELEMENT Phone_No._ (#PCDATA)>
<!ELEMENT Place_Name (#PCDATA)>
<!ELEMENT County (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT User_Name (#PCDATA)>
<!ELEMENT Password (#PCDATA)>

=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/100_Records.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees SYSTEM "100_Records.dtd">
<Employees>
    <Staff>
        <Emp_ID>677509</Emp_ID>
        <Name_Prefix>Drs.</Name_Prefix>
        <First_Name>Lois</First_Name>
        <Middle_Initial>H</Middle_Initial>
        <Last_Name>Walker</Last_Name>
        <Gender>F</Gender>
        <E_Mail>lois.walker@hotmail.com</E_Mail>
        <Father_s_Name>Donald Walker</Father_s_Name>
        <Mother_s_Name>Helen Walker</Mother_s_Name>
        <Mother_s_Maiden_Name>Lewis</Mother_s_Maiden_Name>
        <Date_of_Birth>3/29/1981</Date_of_Birth>
        <Time_of_Birth>02:31:49 AM</Time_of_Birth>
        <Age_in_Yrs.>36.36</Age_in_Yrs.>
        <Weight_in_Kgs.>60</Weight_in_Kgs.>
        <Date_of_Joining>11/24/2003</Date_of_Joining>
        <Quarter_of_Joining>Q4</Quarter_of_Joining>
        <Half_of_Joining>H2</Half_of_Joining>
        <Year_of_Joining>2003</Year_of_Joining>
        <Month_of_Joining>11</Month_of_Joining>
        <Month_Name_of_Joining>November</Month_Name_of_Joining>
        <Short_Month>Nov</Short_Month>
        <Day_of_Joining>24</Day_of_Joining>
        <DOW_of_Joining>Monday</DOW_of_Joining>
        <Short_DOW>Mon</Short_DOW>
        <Age_in_Company__Years_>13.68</Age_in_Company__Years_>
        <Salary>168251</Salary>
        <Last___Hike>21%</Last___Hike>
        <SSN>467-99-4677</SSN>
        <Phone_No._>303-572-8492</Phone_No._>
        <Place_Name>Denver</Place_Name>
        <County>Denver</County>
        <City>Denver</City>
        <State>CO</State>
        <Zip>80224</Zip>
        <Region>West</Region>
        <User_Name>lhwalker</User_Name>
        <Password>DCa}.T}X:v?NP</Password>
    </Staff>
    <Staff>
        <Emp_ID>940761</Emp_ID>
        <Name_Prefix>Ms.</Name_Prefix>
        <First_Name>Brenda</First_Name>
        <Middle_Initial>S</Middle_Initial>
        <Last_Name>Robinson</Last_Name>
        <Gender>F</Gender>
        <E_Mail>brenda.robinson@gmail.com</E_Mail>
        <Father_s_Name>Raymond Robinson</Father_s_Name>
        <Mother_s_Name>Judy Robinson</Mother_s_Name>
        <Mother_s_Maiden_Name>Perry</Mother_s_Maiden_Name>
        <Date_of_Birth>7/31/1970</Date_of_Birth>
        <Time_of_Birth>12:13:27 PM</Time_of_Birth>
        <Age_in_Yrs.>47.02</Age_in_Yrs.>
        <Weight_in_Kgs.>60</Weight_in_Kgs.>
        <Date_of_Joining>7/27/2008</Date_of_Joining>
        <Quarter_of_Joining>Q3</Quarter_of_Joining>
        <Half_of_Joining>H2</Half_of_Joining>
        <Year_of_Joining>2008</Year_of_Joining>
        <Month_of_Joining>7</Month_of_Joining>
        <Month_Name_of_Joining>July</Month_Name_of_Joining>
        <Short_Month>Jul</Short_Month>
        <Day_of_Joining>27</Day_of_Joining>
        <DOW_of_Joining>Sunday</DOW_of_Joining>
        <Short_DOW>Sun</Short_DOW>
        <Age_in_Company__Years_>9.01</Age_in_Company__Years_>
        <Salary>51063</Salary>
        <Last___Hike>27%</Last___Hike>
        <SSN>537-71-4566</SSN>
        <Phone_No._>225-945-4954</Phone_No._>
        <Place_Name>Stonewall</Place_Name>
        <County>De Soto</County>
        <City>Stonewall</City>
        <State>LA</State>
        <Zip>71078</Zip>
        <Region>South</Region>
        <User_Name>bsrobinson</User_Name>
        <Password>TCoj#Zg;SQ~o</Password>
    </Staff>
    <Staff>
        <Emp_ID>428945</Emp_ID>
        <Name_Prefix>Dr.</Name_Prefix>
        <First_Name>Joe</First_Name>
        <Middle_Initial>W</Middle_Initial>
        <Last_Name>Robinson</Last_Name>
        <Gender>M</Gender>
        <E_Mail>joe.robinson@gmail.com</E_Mail>
        <Father_s_Name>Scott Robinson</Father_s_Name>
        <Mother_s_Name>Stephanie Robinson</Mother_s_Name>
        <Mother_s_Maiden_Name>Taylor</Mother_s_Maiden_Name>
        <Date_of_Birth>6/16/1963</Date_of_Birth>
        <Time_of_Birth>10:45:36 AM</Time_of_Birth>
        <Age_in_Yrs.>54.15</Age_in_Yrs.>
        <Weight_in_Kgs.>68</Weight_in_Kgs.>
        <Date_of_Joining>8/3/2016</Date_of_Joining>
        <Quarter_of_Joining>Q3</Quarter_of_Joining>
        <Half_of_Joining>H2</Half_of_Joining>
        <Year_of_Joining>2016</Year_of_Joining>
        <Month_of_Joining>8</Month_of_Joining>
        <Month_Name_of_Joining>August</Month_Name_of_Joining>
        <Short_Month>Aug</Short_Month>
        <Day_of_Joining>3</Day_of_Joining>
        <DOW_of_Joining>Wednesday</DOW_of_Joining>
        <Short_DOW>Wed</Short_DOW>
        <Age_in_Company__Years_>0.98</Age_in_Company__Years_>
        <Salary>50155</Salary>
        <Last___Hike>16%</Last___Hike>
        <SSN>025-92-3584</SSN>
        <Phone_No._>219-904-2161</Phone_No._>
        <Place_Name>Michigantown</Place_Name>
        <County>Clinton</County>
        <City>Michigantown</City>
        <State>IN</State>
        <Zip>46057</Zip>
        <Region>Midwest</Region>
        <User_Name>jwrobinson</User_Name>
        <Password>GO4$J8MiEh[A</Password>
    </Staff>
    <Staff>
        <Emp_ID>408351</Emp_ID>
        <Name_Prefix>Drs.</Name_Prefix>
        <First_Name>Diane</First_Name>
        <Middle_Initial>I</Middle_Initial>
        <Last_Name>Evans</Last_Name>
        <Gender>F</Gender>
        <E_Mail>diane.evans@yahoo.com</E_Mail>
        <Father_s_Name>Jason Evans</Father_s_Name>
        <Mother_s_Name>Michelle Evans</Mother_s_Name>
        <Mother_s_Maiden_Name>Allen</Mother_s_Maiden_Name>
        <Date_of_Birth>12/4/1977</Date_of_Birth>
        <Time_of_Birth>02:18:45 AM</Time_of_Birth>
        <Age_in_Yrs.>39.67</Age_in_Yrs.>
        <Weight_in_Kgs.>51</Weight_in_Kgs.>
        <Date_of_Joining>4/16/1999</Date_of_Joining>
        <Quarter_of_Joining>Q2</Quarter_of_Joining>
        <Half_of_Joining>H1</Half_of_Joining>
        <Year_of_Joining>1999</Year_of_Joining>
        <Month_of_Joining>4</Month_of_Joining>
        <Month_Name_of_Joining>April</Month_Name_of_Joining>
        <Short_Month>Apr</Short_Month>
        <Day_of_Joining>16</Day_of_Joining>
        <DOW_of_Joining>Friday</DOW_of_Joining>
        <Short_DOW>Fri</Short_DOW>
        <Age_in_Company__Years_>18.3</Age_in_Company__Years_>
        <Salary>180294</Salary>
        <Last___Hike>1%</Last___Hike>
        <SSN>314-35-9851</SSN>
        <Phone_No._>215-793-6791</Phone_No._>
        <Place_Name>Hydetown</Place_Name>
        <County>Crawford</County>
        <City>Hydetown</City>
        <State>PA</State>
        <Zip>16328</Zip>
        <Region>Northeast</Region>
        <User_Name>dievans</User_Name>
        <Password>0gGRtp1HfL&lt;r5</Password>
    </Staff>
    <Staff>
        <Emp_ID>193819</Emp_ID>
        <Name_Prefix>Mr.</Name_Prefix>
        <First_Name>Benjamin</First_Name>
        <Middle_Initial>R</Middle_Initial>
        <Last_Name>Russell</Last_Name>
        <Gender>M</Gender>
        <E_Mail>benjamin.russell@charter.net</E_Mail>
        <Father_s_Name>Gregory Russell</Father_s_Name>
        <Mother_s_Name>Elizabeth Russell</Mother_s_Name>
        <Mother_s_Maiden_Name>Nelson</Mother_s_Maiden_Name>
        <Date_of_Birth>4/17/1977</Date_of_Birth>
        <Time_of_Birth>05:41:11 PM</Time_of_Birth>
        <Age_in_Yrs.>40.31</Age_in_Yrs.>
        <Weight_in_Kgs.>58</Weight_in_Kgs.>
        <Date_of_Joining>7/25/2013</Date_of_Joining>
        <Quarter_of_Joining>Q3</Quarter_of_Joining>
        <Half_of_Joining>H2</Half_of_Joining>
        <Year_of_Joining>2013</Year_of_Joining>
        <Month_of_Joining>7</Month_of_Joining>
        <Month_Name_of_Joining>July</Month_Name_of_Joining>
        <Short_Month>Jul</Short_Month>
        <Day_of_Joining>25</Day_of_Joining>
        <DOW_of_Joining>Thursday</DOW_of_Joining>
        <Short_DOW>Thu</Short_DOW>
        <Age_in_Company__Years_>4.01</Age_in_Company__Years_>
        <Salary>117642</Salary>
        <Last___Hike>13%</Last___Hike>
        <SSN>121-98-7248</SSN>
        <Phone_No._>262-404-2252</Phone_No._>
        <Place_Name>Fremont</Place_Name>
        <County>Waupaca</County>
        <City>Fremont</City>
        <State>WI</State>
        <Zip>54940</Zip>
        <Region>Midwest</Region>
        <User_Name>brrussell</User_Name>
        <Password>Rd&lt;Y8cp!@R;*%F</Password>
    </Staff>
    <Staff>
        <Emp_ID>499687</Emp_ID>
        <Name_Prefix>Mr.</Name_Prefix>
        <First_Name>Patrick</First_Name>
        <Middle_Initial>F</Middle_Initial>
        <Last_Name>Bailey</Last_Name>
        <Gender>M</Gender>
        <E_Mail>patrick.bailey@aol.com</E_Mail>
        <Father_s_Name>Ralph Bailey</Father_s_Name>
        <Mother_s_Name>Laura Bailey</Mother_s_Name>
        <Mother_s_Maiden_Name>Henderson</Mother_s_Maiden_Name>
        <Date_of_Birth>9/27/1982</Date_of_Birth>
        <Time_of_Birth>01:12:41 PM</Time_of_Birth>
        <Age_in_Yrs.>34.86</Age_in_Yrs.>
        <Weight_in_Kgs.>58</Weight_in_Kgs.>
        <Date_of_Joining>7/22/2005</Date_of_Joining>
        <Quarter_of_Joining>Q3</Quarter_of_Joining>
        <Half_of_Joining>H2</Half_of_Joining>
        <Year_of_Joining>2005</Year_of_Joining>
        <Month_of_Joining>7</Month_of_Joining>
        <Month_Name_of_Joining>July</Month_Name_of_Joining>
        <Short_Month>Jul</Short_Month>
        <Day_of_Joining>22</Day_of_Joining>
        <DOW_of_Joining>Friday</DOW_of_Joining>
        <Short_DOW>Fri</Short_DOW>
        <Age_in_Company__Years_>12.02</Age_in_Company__Years_>
        <Salary>72305</Salary>
        <Last___Hike>5%</Last___Hike>
        <SSN>439-99-7721</SSN>
        <Phone_No._>319-812-6957</Phone_No._>
        <Place_Name>Macksburg</Place_Name>
        <County>Madison</County>
        <City>Macksburg</City>
        <State>IA</State>
        <Zip>50155</Zip>
        <Region>Midwest</Region>
        <User_Name>pfbailey</User_Name>
        <Password>K7&amp;5aY/*</Password>
    </Staff>
    <Staff>
        <Emp_ID>539712</Emp_ID>
        <Name_Prefix>Ms.</Name_Prefix>
        <First_Name>Nancy</First_Name>
        <Middle_Initial>T</Middle_Initial>
        <Last_Name>Baker</Last_Name>
        <Gender>F</Gender>
        <E_Mail>nancy.baker@bp.com</E_Mail>
