=== AIMoney808/SchoolProjects/MCC/INFO_2351/final_project/games.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" maxOccurs="unbounded"/>
                <xs:element ref="game" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="game">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="publisher"/>
                <xs:element ref="releaseDate"/>
                <xs:element ref="genre"/>
                <xs:element ref="value"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="title">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:minLength value="5"/>
                <xs:maxLength value="30"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="publisher" type="xs:string"/>
    <xs:element name="releaseDate" type="xs:date"/>
    <xs:element name="genre" type="xs:string"/>
    <xs:element name="value">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="\$\d{1,4}\.\d{2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

</xs:schema>

=== AIMoney808/SchoolProjects/MCC_2018-2022/INFO_2351/final_project/games.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="fin.xslt"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="games.xsd">
    <name>Games in the Library</name>
    <game>
        <title>Elden Ring</title>
        <publisher>FromSoftware Inc.</publisher>
        <releaseDate>2022-02-24</releaseDate>
        <genre>Action/RPG</genre>
        <value>$59.99</value>
    </game>
    <game>
        <title>Borderlands</title>
        <publisher>2K</publisher>
        <releaseDate>2009-10-20</releaseDate>
        <genre>Action/RPG</genre>
        <value>$29.99</value>
    </game>
    <game>
        <title>Risk of Rain 2</title>
        <publisher>Gearbox Publishing</publisher>
        <releaseDate>2020-08-11</releaseDate>
        <genre>Action/Indie</genre>
        <value>$24.99</value>
    </game>
    <game>
        <title>Hardspace: Shipbreaker</title>
        <publisher>Focus Entertainment</publisher>
        <releaseDate>2020-06-16</releaseDate>
        <genre>Simulation</genre>
        <value>$34.99</value>
    </game>
    <game>
        <title>Stardew Valley</title>
        <publisher>ConcernedApe</publisher>
        <releaseDate>2016-02-26</releaseDate>
        <genre>Indie/RPG/Simulation</genre>
        <value>$15.99</value>
    </game>
</library>
